### ISSUE TITLE
데이터 문의

### ISSUE THREAD

**Issue by gyunggyung** [nawnoes/NarrativeKoGPT2#1]
안녕하세요. 혹시 학습에 사용하신 데이터 공유가 가능하실까요?

감사합니다 :)

**Comment by nawnoes** [comment]
안녕하세요!

소량의 인터넷 소설과 소설 데이터로 테스트 해보고 있는데,
저작권 문제로 공유는 어려울거 같습니다 ㅠ

이 레포지토리는 혼자 개발 할 때, 임시로 진행해서 지울 예정이라, 
추가 문의는 https://github.com/shbictai/narrativeKoGPT2 여기로 부탁드리겠습니다!

감사합니다!
